### ISSUE TITLE
Sign of Estimated FRF’s Phase Angle is Inverted

### ISSUE THREAD

**Issue by a1hermit** [ladisk/pyFRF#14]
pyFRF reports conjugate of FRF as estimated FRF due to using wrong cross spectral density.
For example, when it calculates H1 estimator, the code use “S_XF / S_FF” instead of “S_FX / S_FF” as the estimator.

**Comment by jankoslavic** [comment]
Thank you @a1hermit you are indeed right. Also in H2 estimator the phase looks inverted. 
Please give me some time to check if there is a reason why we did it like this and to setup a proper test for this.

**Comment by jankoslavic** [comment]
@a1hermit the issue should now be handled; @domengorjup made a throughout review and added tests with this PR: https://github.com/ladisk/pyFRF/pull/15

The PR is now merged into the main branch. I ask you to double check it and give feedback here.

**Comment by jankoslavic** [comment]
I am closing this issue now.
