### ISSUE TITLE
PyPI version is outdated

### ISSUE THREAD

**Issue by OliverZobel** [ladisk/pyFRF#16]
The version on PyPI is outdated and still has some issues fixed in the code, e.g., the wrong phase. We tried modal ID with pyFBS using pyFRF's FRFs and the ID failed due to the wrong phase. Using the code on GitHub works. Could you please update the PyPI version?

**Comment by jankoslavic** [comment]
Thank you @OliverZobel . This is done:) I hope to see you at OpenSD2025 :)
https://www.ladisk.si/OpenSDconference.php
