### ISSUE TITLE
Performing FRF - Vibration

### ISSUE THREAD

**Issue by guiamuchastegui** [ladisk/pyFRF#5]
I am trying to use your package pyFRF to perform an FRF for ODS measurement. 
I need to perform FRF between 2 data from accelerometer, which is in g unit. 
 
I need as output H1 and phase information. 
 
Reading the examples at the  “showcase page” (https://github.com/openmodal/pyFRF/blob/master/Showcase%20pyFRF.ipynb) I get confused in some points:
- What are the order and mandatory input in the pyFRF?
              - i.e – frf = FRF( sampling frequency, excitation, response, excitation window, response type, response window) ? or…
              - i.e – frf = FRF(sampling frequency, fft length, excitation window, response window, response type, weighting , n_averages)  -  in this case it is not clear where I have to input excitation and response signal?

- What are the response type option?
 
 
Others question that you can help me if possible:
- Can I integrate the acceleration signal and perform ODS? (i.e velocity unit)
- What is the units when I perform FRF based on the same measurement?
              - Since we are splitting the same unit, I am pretty sure that is non dimensional….although I was looking for some technical material that can show how to deal with the real and imaginary part of the equations and perform the dimensional analysis in this equation.
 
Any help it is welcome.

**Comment by jankoslavic** [comment]
Dear @guiamuchastegui 

pyFRF has the capability to perform FRF in two ways:
* `FRF( sampling frequency, excitation, response, excitation window, response type, response window)` is the typical usage for obtaining a FRF **after** the measurement is finished
* `FRF(sampling frequency, fft length, excitation window, response window, response type, weighting , n_averages)` is used to perform FRF **during** your measurement. In this case you add data via the method `.add_data()`. With this you can continuously update to the user interface (after each measurement a new averaged FRF can be shown). In the showcase, the data is added in cell 35.

Response options? Please see the code:
* `_EXC_TYPES = ['f', 'a', 'v', 'd', 'e']`  # force for EMA and kinematics for OMA
* `_RESP_TYPES = ['a', 'v', 'd', 'e']`  # **acceleration, velocity, displacement, strain**

ODS?
Research the cell 26: call the method `.get_ods_frf()`

Units?
If you are using SI units which correspond to the excitation and response node you defined when creating the instance of object FRF, all units should be handled accordingly. See cell 26 on how to access: accelerance, mobility, receptance.
