### ISSUE TITLE
Missing citation?

### ISSUE THREAD

**Issue by canbooo** [ladisk/pyFRF#7]
Is there a way to cite pyFRF or openmodal in an academical context? Most journals are not happy with github links or webpages.

**Comment by jankoslavic** [comment]
Dear @canbooo, I am sorry, we currently do not have a dedicated reference for pyFRF. For pyFRF I currently do not see other option than the github link. If you would like to say "thank you", maybe you will find a content-wise reference within our peer-reviewed publications here: http://lab.fs.uni-lj.si/ladisk/?what=incfl&flnm=research_en.php&

**Comment by canbooo** [comment]
Thank you for you kind answer @jankoslavic, I guess I can cite github in combination with 

> An interface force measurements-based substructure identification and an analysis of the uncertainty propagation

e.g. "as described in [Paper] and implemented in [Github]." Closing the issue.
